//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.09 at 11:57:18 ¤W¤È CST 
//


package gtu.jaxb.ex1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gtu.jaxb.ex1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Sugers_QNAME = new QName("http://www.WhiteSugerCompany.com/ws", "Sugers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gtu.jaxb.ex1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Suger }
     * 
     */
    public Suger createSuger() {
        return new Suger();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Suger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.WhiteSugerCompany.com/ws", name = "Sugers")
    public JAXBElement<Suger> createSugers(Suger value) {
        return new JAXBElement<Suger>(_Sugers_QNAME, Suger.class, null, value);
    }

}
