package gtu.soap.apacheCxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T20:03:55.794+08:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "BANCSServiceService",
                  wsdlLocation = "file:/C:/Users/E123474/Desktop/BANCSService.xml",
                  targetNamespace = "http://webservice.cathaybk.com.tw")
public class BANCSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.cathaybk.com.tw", "BANCSServiceService");
    public final static QName BANCSService = new QName("http://webservice.cathaybk.com.tw", "BANCSService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/E123474/Desktop/BANCSService.xml");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BANCSService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/E123474/Desktop/BANCSService.xml");
        }
        WSDL_LOCATION = url;
    }

    public BANCSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BANCSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BANCSService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BANCSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BANCSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BANCSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BANCSService
     */
    @WebEndpoint(name = "BANCSService")
    public BANCSServiceSoap getBANCSService() {
        return super.getPort(BANCSService, BANCSServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BANCSService
     */
    @WebEndpoint(name = "BANCSService")
    public BANCSServiceSoap getBANCSService(WebServiceFeature... features) {
        return super.getPort(BANCSService, BANCSServiceSoap.class, features);
    }

}
