package gtu.soap.apacheCxf;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import gtu.soap.apacheCxf.dto.ObjectFactory;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-06-03T20:03:55.762+08:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://webservice.cathaybk.com.tw", name = "BANCSService")
@XmlSeeAlso({ObjectFactory.class})
public interface BANCSServiceSoap {

    @WebMethod(operationName = "XServiceMethod")
    @RequestWrapper(localName = "XServiceMethod", targetNamespace = "http://webservice.cathaybk.com.tw", className = "tw.com.cathaybk.webservice.XServiceMethod")
    @ResponseWrapper(localName = "XServiceMethodResponse", targetNamespace = "http://webservice.cathaybk.com.tw", className = "tw.com.cathaybk.webservice.XServiceMethodResponse")
    @WebResult(name = "XServiceMethodReturn", targetNamespace = "http://webservice.cathaybk.com.tw")
    public java.lang.String xServiceMethod(

        @WebParam(name = "RequstXML", targetNamespace = "http://webservice.cathaybk.com.tw")
        java.lang.String requstXML
    );

    @WebMethod(operationName = "ECHO")
    @RequestWrapper(localName = "ECHO", targetNamespace = "http://webservice.cathaybk.com.tw", className = "tw.com.cathaybk.webservice.ECHO")
    @ResponseWrapper(localName = "ECHOResponse", targetNamespace = "http://webservice.cathaybk.com.tw", className = "tw.com.cathaybk.webservice.ECHOResponse")
    @WebResult(name = "ECHOReturn", targetNamespace = "http://webservice.cathaybk.com.tw")
    public java.lang.String echo(

        @WebParam(name = "RequestString", targetNamespace = "http://webservice.cathaybk.com.tw")
        java.lang.String requestString
    );
}
