server:
  port: 8080
  
---
spring:
  profiles:
    active: local
---    

spring:
  datasource:
    derby :
      url: jdbc:derby://localhost:1527/seconddb;create=true
      username: test
      password: 1234
      driver-class-name: org.apache.derby.jdbc.ClientDriver
      test-on-borrow: false
      
