--utf8 文件 generated by DDM
--exported from TGL_MAIN_DEV
update T_COMMON_AUTH_ITEM set  (ITEM_ID,ITEM_NAME,LIMITATION_TYPE,PARENT_ID) 
= ( select 13,'懸帳查詢頁面查詢權限',91,null from dual ) where ITEM_ID=13;
insert into T_COMMON_AUTH_ITEM (ITEM_ID,ITEM_NAME,LIMITATION_TYPE,PARENT_ID) 
select 13,'懸帳查詢頁面查詢權限',91,null from dual where not exists (select * from T_COMMON_AUTH_ITEM where ITEM_ID=13);
