SELECT XXTP01.EMP_ID,
       XXTP01.EMP_NAME,
       XXTP01.DIV_NO,
       XXTP01.BIRTHDAY,
       XXTP01.POSITION,
       XXTP01.UPDT_ID,
       XXTP01.FLOW_NO,
       XXTP01.OP_STATUS,
       EMPLOYEE.NAME UPDT_NM,
       XXTP01.UPDT_DATE UPDT_DATE,
       UNIT_WORK.DIV_SHORT_NAME DIV_NO_NM
  FROM DBXX.DTXXTP01 XXTP01
       LEFT JOIN CXLHR.DTA0_EMPLOYEE_WORK EMPLOYEE
          ON XXTP01.UPDT_ID = EMPLOYEE.EMPLOYEE_ID
       LEFT JOIN CXLHR.DTZ0_UNIT_WORK UNIT_WORK
          ON XXTP01.DIV_NO = UNIT_WORK.DIV_NO
 WHERE     1 = 1
       [ AND XXTP01.EMP_ID = ':EMP_ID' ]
       [ AND XXTP01.DIV_NO LIKE ':DIV_NO' ]
  WITH UR
