FROM ubuntu 
LABEL maintainer="gtu001@gmail.com"

ENV downloads /downloads

RUN apt update -y && apt upgrade -y && apt-get install -y \
		vim \
		iptables \
		less \
		debconf \
		curl \
		netcat-openbsd \
		net-tools \
		netcat \
		wget
		


