spring:
  application:
    name: mima-cloud-eureka


server:
  port: ${port:8761}  # HTTP port 
  compression:
    enabled: true
    
 
#eureka server   
eureka:   #此处设置会改变eureka控制台的显示
  datacenter: cloud #此处设置会改变eureka控制台的显示
  environment: prod
  dashboard: #控制台路径
    path: /dashboard  #http://localhost:8761/dashboard   #是否启用控制台
    enabled: true
  instance:  #实例主机名
    hostname: localhost
    leaseRenewalIntervalInSeconds : 30
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://user:password@localhost:8761}/eureka/   
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    renewalPercentThreshold : 5
    
    

security:
  basic:
    enabled: false    #关闭安全验证
    
