spring:
  application:
    name: rest-test-001


server:
  port: ${port:9000}
  compression:
    enabled: true


#eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
      
      
