spring:
  application:
    name: rest_test_001

server:
  port: ${port:9000}
  compression:
    enabled: true

#eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/