CREATE TABLE TEST.EMPLOYEE (
	EMPLOYEE_ID BIGINT NOT NULL,
	DESCRIPTION VARCHAR(100),
	FIRSTNAME VARCHAR(100),
	LASTNAME VARCHAR(100),
	TEST_NUM INTEGER,
	CREATED_AT TIMESTAMP,
	UPDATED_AT TIMESTAMP
);
