package gtu.hibernate2;

// default package
// Generated Jun 26, 2012 10:37:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserId generated by hbm2java
 */
public class UserId implements java.io.Serializable {

    private String userId;
    private String userName;
    private String userPassword;

    public UserId() {
    }

    public UserId(String userId, String userName, String userPassword) {
        this.userId = userId;
        this.userName = userName;
        this.userPassword = userPassword;
    }

    public String getUserId() {
        return this.userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getUserPassword() {
        return this.userPassword;
    }

    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    public boolean equals(Object other) {
        if ((this == other))
            return true;
        if ((other == null))
            return false;
        if (!(other instanceof UserId))
            return false;
        UserId castOther = (UserId) other;

        return ((this.getUserId() == castOther.getUserId()) || (this.getUserId() != null && castOther.getUserId() != null && this.getUserId().equals(castOther.getUserId())))
                && ((this.getUserName() == castOther.getUserName()) || (this.getUserName() != null && castOther.getUserName() != null && this.getUserName().equals(castOther.getUserName())))
                && ((this.getUserPassword() == castOther.getUserPassword()) || (this.getUserPassword() != null && castOther.getUserPassword() != null && this.getUserPassword().equals(
                        castOther.getUserPassword())));
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + (getUserId() == null ? 0 : this.getUserId().hashCode());
        result = 37 * result + (getUserName() == null ? 0 : this.getUserName().hashCode());
        result = 37 * result + (getUserPassword() == null ? 0 : this.getUserPassword().hashCode());
        return result;
    }

}
