package gtu.hibernate2;

// default package
// Generated Jun 26, 2012 10:37:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private UserId id;

    public User() {
    }

    public User(UserId id) {
        this.id = id;
    }

    public UserId getId() {
        return this.id;
    }

    public void setId(UserId id) {
        this.id = id;
    }

}
