spring:
  application:
    name: limits-service
    
---

spring:
  profiles:
    active: native


---

server:
  port: ${port:8090}
  compression:
    enabled: true
---



limits-service:
  minimum=99  
  maximum=9999  
  
  
---
spring:
  cloud:
    config:
      server:
        native:
          searchLocations=file://C:/Users/wistronits/Desktop/application.yml
        bootstrap: true
          

          
          
