spring:
  application:
    name: test001
    



---

server:
  port: ${port:8090}
  compression:
    enabled: true
---



limits-service:
  minimum=99  
  maximum=9999  
  
  

---
#jpa
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create 
  h2.console.enabled: true
  datasource:
    platform: h2
    url: jdbc:h2:file:D:\workstuff\gtu-test-code\_SpringBootTestProject\h2\testDB;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  h2.jar.position: D:\my_tool\FastDBQueryUI/h2-1.4.197.jar
  h2.script: classpath:gtu/test/jpa/exchange_value_01.sql




---
#feign
employee-producer:
  ribbon:
    listOfServers: http://localhost:8090

github-test-producer:
  ribbon:
    listOfServers: https://my-json-server.typicode.com/gtu001/fake_json_server/
    
XXXXXXXXXXXXXXXXXXXXXXX:
  ribbon:
    listOfServers: https://my-json-server.typicode.com/gtu001/fake_json_server/

 
eureka:
  instance:
    hostname: localhost
  client:
    #register-with-eureka: false
    register-with-eureka: true
    fetch-registry: false
    #注册中心地址
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/




