package gtu.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class AutoGeneratedKeysTest {

    public static void main(String[] args) throws SQLException {
        Connection conn = null;//TODO
        PreparedStatement pstmt = conn.prepareStatement("some update or insert sql", //
                Statement.RETURN_GENERATED_KEYS);
        //or ... 
        pstmt.executeUpdate(null, Statement.RETURN_GENERATED_KEYS);
        //then
        ResultSet rs = pstmt.getGeneratedKeys();
        if (rs.next()) {
            rs.getInt(0); //取得PK
        }
    }
}
